# Changes here will be overwritten by Copier
_src_path: gh:jaeyeom/bazel-project-template
_commit: 91dc4addcba0f4409ab8732523b3f6dcb9c0a269
repo_name: "sugo"
project_description: "Sugo offers handy syntactic sugar (though not technically a syntactic sugar) for Go, designed to simplify your code and save you time."
github_owner: "jaeyeom"
languages: [go]
go_version: "1.24.2"
go_module_path: "github.com/jaeyeom/sugo"
python_version: "3.14"
bazel_version: "8.5.0"
author_name: "Jaehyun Yeom"
author_email: "jae.yeom@gmail.com"
